/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 date_fruit.glb --transform --simplify
Author: JNO_Models (https://sketchfab.com/Jamlnid)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/date-fruit-b6f9e82bf63842dbb40cc6503376e90e
Title: Date Fruit
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/date_fruit-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['polySurface1_01_-_Default_0'].geometry} material={materials['01_-_Default']} position={[0, -0.34, 0]} rotation={[0, 0, -Math.PI]} scale={0.008} />
    </group>
  )
}

useGLTF.preload('/date_fruit-transformed.glb')
