/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 star_wars_-_halcon_milenario.glb --transform
Author: albertomarun (https://sketchfab.com/albertomarun)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/star-wars-halcon-milenario-d2be38faf4124fb9839853bedce5bcce
Title: Star Wars - Halcon Milenario
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/star_wars_-_halcon_milenario-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.CP_Front} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_3.geometry} material={materials.Cockpit2} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_4.geometry} material={materials.Cockpit3} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.Dish01} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.Dish02} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.DrivBack} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.Engine01} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.Engine02} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_10.geometry} material={materials.M_Inside} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.MandbEnd} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_12.geometry} material={materials.PodSide1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.SidePort} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_14.geometry} material={materials.SideRear} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.SideRear1} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_16.geometry} material={materials.Turret_L} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.DishSide} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_18.geometry} material={materials.EscPod_L} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.EscPod_U} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_20.geometry} material={materials.FalcPlan} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.FalcUndr} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.FrontColor} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_24.geometry} material={materials.Hatch} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.Turret_U} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Vent01} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.Charcoal_1} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/star_wars_-_halcon_milenario-transformed.glb')
